# Generated by Django 3.2.4 on 2021-06-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobNo',
            new_name='mob',
        ),
    ]
