# Generated by Django 3.2.4 on 2021-06-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0002_rename_mobno_student_mob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mob',
            new_name='ph',
        ),
    ]
