# Generated by Django 3.2.4 on 2021-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0003_rename_mob_student_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
